# Generated by Django 5.0.1 on 2024-03-28 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='is_IRL',
            new_name='is_irl',
        ),
    ]
