# Generated by Django 5.0.1 on 2024-03-28 20:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=500)),
                ('club_description', models.TextField(blank=True, max_length=10000, null=True)),
                ('permission_type', models.CharField(choices=[('IO', 'Invite only'), ('RTJ', 'Request to join'), ('P', 'Public')], max_length=500)),
                ('admins', models.ManyToManyField(related_name='admins', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
